# -*-Makefile-*- for fft_check
##
FC=ifort
FFLAGS=-free -r8 -O3 -warn all -openmp -openmp-report2 -parallel -par-report1
CPPFLAGS=-DHAVE_LIBFFTW3 -I/uhome/s21584/Linux-x86_64/include
LDFLAGS=-L/uhome/s21584/Linux-x86_64/lib -lmkl_intel_thread -lfftw3 -lfftw3_omp -lmkl_core

fft_check: fft_check.o f90_wisdom.o
	$(FC) $(FFLAGS) -o $@ $^ $(LDFLAGS)
clean:
	rm -f core* fft_check fft_check.o f90_wisdom.o *__genmod.mod *__genmod.f90
