# -*-Makefile-*- for fft_check
##
FC=gfortran
FFLAGS=-Wall -O3 -fopenmp -ffree-form -ffree-line-length-none
CPPFLAGS=-DHAVE_LIBFFTW3 -I/home/t-nissie/Linux-x86_64/include
LDFLAGS=-lfftw3 -lfftw3_omp \
 -L/home/t-nissie/Linux-x86_64/lib64

fft_check: fft_check.o f90_wisdom.o
	$(FC) $(FFLAGS) -o $@ $^ $(LDFLAGS)
clean:
	rm -f core* fft_check fft_check.o f90_wisdom.o
